/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 *       strict-local
 */

'use strict';

             
            
             
             
             
         
              
                                    
                                                                        
                                
                                                               
             
                    
                     
                     
                           
                          
                             

                                
                                          

                                      
                                        
                                          
    

                                    
     
                                                                           
                                                           
    
     
                                                                      

     
                                                                           
                                                      
    
                                                                  
     
                                    

     
                                              
    
                                                      
    
                                                                             
                                                                          
                                                                        
    
                                                        
     
                                            

     
                                                                               
                                         
    
                                                          
     
                            

     
                                                                               
                                      
    
                                                                     
     
                                       
    

                                   
                                             
                                             
    

                                   
                                           
                                                  
                                        
                                               
                                         
                                                
                                          
                                                 
    

/**
 * For most touch interactions, you'll simply want to wrap your component in
 * `TouchableHighlight` or `TouchableOpacity`. Check out `Touchable.js`,
 * `ScrollResponder.js` and `ResponderEventPlugin.js` for more discussion.
 */
                                              
     
                                                                            
                                                                 
    
                                                                            
                                                           
    
                                                                        
     
                                                         

     
                                                                               
                                                                 
    
                                                                             
                                                                 
    
                                                                               
     
                                                                

     
                                                                               
                                         
    
                                                                               
                                    
    
                                                                                             
                                         
    
                                                                
     
                                                        

     
                                     
    
                                                                              
                                    
    
                                                               
     
                                             

     
                                                                               
                                
    
                                                                      
                                              
    
                                                                 
     
                                               

     
                                   
    
                                                                       
                                              
    
                                                                  
     
                                                

                                              
                                            

     
                                                                          
                                                                             
                                                                              
                   
    
                                                                         
                                              
    
                                                                    
     
                                                  

     
                                                                             
                                                                
    
                                                                             
                                                   
    
                                                                             
     
                                                              

     
                                                                     
    
                                                                             
                                                           
    
                                                                         
     
                                                          

     
                                                                               
                                                                        
    
                                                                              
                                                                 
    
                                                                                
     
                                                                 
    

                                            
                           
                    
    

                                         
                        
                  
                        
                         
    

                                                                        

                                    
                                             
                                             

     
                                                                              
                                        
    
                      
    
                                                                              
     
                                            

     
                                                                              
                                                                          
                                                                                
                                                                 
    
                      
    
                                                           
     
                         

     
                                                                           
                                                                          
    
                      
    
                                                                              
     
                                            

     
                                                                            
                                                              
    
                      
    
                                                                       
     
                                                               

     
                                                                    
                                                                               
                                                   
    
                      
    
                                                                         
     
                                                                               

     
                                                                             
    
                      
     
                                 

     
                                                                   
    
                      
     
                          

     
                                                                      
    
                      
     
                             

     
                                                                   
    
                      
     
                          

     
                                                                    
    
                      
     
                           

     
                                                                 
    
                      
     
                        

     
                                                                                                                       
    
                      
     
                      

     
                                                                                                                     
    
                      
     
                                          
    

                                
     
                                                                                       
    
                  
     
                                              

     
                                                                    
                                                    
                        
    
                  
    
                                                                        
     
                                      

     
                                                                           
                                           
    
                  
    
                                                                           
     
                                         

     
                                                                           
    
                  
    
                                                                  
     
                                
    

                                    
                        
                      
                                
                     
                     
                      
                  

                  
                         

     
                                                                      
                                                           
    
                                                          
     
                        

     
                                                                                
                                                                             
                                                                           
    
                                                                  
     
                                  

     
                                                                                    
                                                                                    
                         
    
    
                                                                 
     
                                 

     
                                                                                    
     
                                         

     
                                                                                  
     
                                           
                                           

     
                                                                     
    
     
                                                                  

     
                                                  
    
                                                                               
    
                                                      
     
                   

     
                                                  
    
                                                                               
    
                                                        
     
                     

     
                                                                     
                                                                           
                                               
    
                                                                               
                                                                               
             
    
                                                       
     
                            

     
                                                                   
    
                                                             
     
                                                               

     
                                                                              
                                                                          
                                                                          
                                                                        
                                                                              
                                
    
                                                                     
     
                                   
    
